config/routes.rb
SomethingNotCool::Application.routes.draw do
  resources :mixes
  root :to => "mixes#index"

end

app/models/mix.rb
class Mix < ActiveRecord::Base
  attr_accessible :url1, :url2, :offset1, :offset2
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  # GET /mixes
  # GET /mixes.json
  def index
    @mixes = Mix.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixes }
    end
  end

  # GET /mixes/1
  # GET /mixes/1.json
  def show
    @mix = Mix.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/new
  # GET /mixes/new.json
  def new
    @mix = Mix.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/1/edit
  def edit
    @mix = Mix.find(params[:id])
  end

  # POST /mixes
  # POST /mixes.json
  def create
    @mix = Mix.new(params[:mix])

    respond_to do |format|
      if @mix.save
        format.html { redirect_to @mix, notice: 'Mix was successfully created.' }
        format.json { render json: @mix, status: :created, location: @mix }
      else
        format.html { render action: "new" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixes/1
  # PUT /mixes/1.json
  def update
    @mix = Mix.find(params[:id])

    respond_to do |format|
      if @mix.update_attributes(params[:mix])
        format.html { redirect_to @mix, notice: 'Mix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix = Mix.find(params[:id])
    @mix.destroy

    respond_to do |format|
      format.html { redirect_to mixes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SomethingNotCool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mixes/_form.html.erb
<%= form_for(@mix) do |f| %>
  <% if @mix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mix.errors.count, "error") %> prohibited this mix from being saved:</h2>

      <ul>
      <% @mix.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url1 %><br />
    <%= f.text_field :url1 %>
  </div>
  <div class="field">
    <%= f.label :offset1 %><br />
    <%= f.text_field :offset1 %>
  </div>

    <div class="field">
    <%= f.label :url2 %><br />
    <%= f.text_field :url2 %>
  </div>

  <div class="field">
    <%= f.label :offset2 %><br />
    <%= f.text_field :offset2 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mixes/edit.html.erb
<h1>Editing mix</h1>

<%= render 'form' %>

<%= link_to 'Show', @mix %> |
<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<h1>Listing mixes</h1>

<table>
  <tr>
    <th>Url1</th>
    <th>Url2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mixes.each do |mix| %>
  <tr>
    <td><%= mix.url1 %></td>
    <td><%= mix.url2 %></td>
    <td><%= link_to 'Show', mix %></td>
    <td><%= link_to 'Edit', edit_mix_path(mix) %></td>
    <td><%= link_to 'Destroy', mix, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mix', new_mix_path %>

app/views/mixes/new.html.erb
<h1>New mix</h1>

<%= render 'form' %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url1:</b>
  <%= @mix.url1 %>
  </p>


  <iframe class="youtube-player" type="text/html" width="320" height="200" src="http://www.youtube.com/embed/<%= @mix.url1.split('v=')[1] %>?autoplay=1&start=<%= @mix.offset1 %>" frameborder="0">
</iframe>


<p>
  <b>Url2:</b>
  <%= @mix.url2 %>
</p>


  <iframe class="youtube-player" type="text/html" width="320" height="200" src="http://www.youtube.com/embed/<%= @mix.url2.split('v=')[1] %>?autoplay=1&start=<%= @mix.offset2 %>"" frameborder="0">
</iframe>



<%= link_to 'Edit', edit_mix_path(@mix) %> |
<%= link_to 'Back', mixes_path %>